# pip install numpy

In [2]:
import numpy as np
mylist = [1,2,3,4,5]
mynum = np.array(mylist)
print(mynum)
type(mylist)

[1 2 3 4 5]


list

In [18]:
num2 = np.array([1,2,4])
num2

array([1, 2, 4])

In [19]:
num3 = np.array((1,2,4))
num3

array([1, 2, 4])

In [20]:
num4 = np.array({4,5,6})
num4

array({4, 5, 6}, dtype=object)

In [21]:
print(type(num4))

<class 'numpy.ndarray'>


In [26]:
A = [1.5,2,3,5]
B = (4,5,6,7)
A = np.array(A)
B = np.array(B)
type(A)
type(B)
print((A+B)*B)

[22. 35. 54. 84.]


In [23]:
print(A-B)
print(A*B)
print(A/B)

[-3 -3 -3 -2]
[ 4 10 18 35]
[0.25       0.4        0.5        0.71428571]


In [27]:
print(A.dtype)

float64


In [31]:
data = [20,30,31,35,40,42]
print(np.mean(data))
print(np.max(data))
print(np.min(data))
print(np.sum(data))

33.0
42
20
198


In [16]:
import numpy as np
data = np.random.randint(1,100,(10,10))
data

array([[32, 36, 27, 79, 12, 28, 34, 73, 61, 95],
       [37, 96, 40, 41,  9, 35,  8,  5, 79, 63],
       [ 2, 80, 76, 62, 17,  8, 42,  1, 35, 51],
       [ 4, 79, 42, 44, 79, 74, 20, 78, 97, 18],
       [46, 99, 32, 77, 88, 67, 91, 69, 49, 27],
       [32, 29, 12, 23, 60,  4, 44, 63, 81, 16],
       [53, 27, 63, 10, 14, 83, 89, 68, 41, 33],
       [80, 57,  7, 99, 16, 63, 85,  5, 83, 44],
       [35, 10, 23, 55, 73, 65, 74, 60, 86, 83],
       [26, 35, 68, 76, 49, 91, 79, 40, 86, 83]], dtype=int32)

In [3]:
A = np.array([1,2,3,4])
A

array([1, 2, 3, 4])

In [5]:
B = [[1,2,3],
     [1,2,3],
     [2,3,4]]
B = np.array(B)
B

array([[1, 2, 3],
       [1, 2, 3],
       [2, 3, 4]])

In [7]:
C = [[[1,2],[2,3]],[[2,3],[5,6]],[[4,5],[4,6]]]
C = np.array(C)
print(C.shape)

(3, 2, 2)


In [8]:
D =  [[[1,2,6],[2,4,3]],[[2,3,7],[5,4,6]]]
D = np.array(D)
print(D.shape)

(2, 2, 3)


In [ ]:
arr = np.zeros(5)
arr = np.zeros((4,4))
arr = np.ones(5)
arr = np.ones((5,5),dtype=int)
arr = np.full((10,10),7)


print(arr)

[[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]


In [25]:
arr = np.array((True,False))
arr

array([ True, False])

In [59]:
import numpy as np

t = np.array([1,2,3,4])
arr = np.array( [[10,20,30],
                [100,200,300],
                [1000,2000,3000],
                [10000,20000,30000]])

t[0:4]
arr[0:2,0:2]
arr[1:4,2]
arr[1:,2:]

array([[  300],
       [ 3000],
       [30000]])

In [9]:
import numpy as np
v = np.empty(4,dtype='int32')
v = np.empty([4,4],dtype='float')
v

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        2.12199579e-314]])

In [31]:
a = np.identity(4)
a = np.identity(5,dtype='int')
print(a)
for i in range(len(a)):
    for j in range(len(a)):
        if a[i,j] == 1:
            a[i,j] = 3
print(a)


b = np.identity(5,dtype=int)
print(b)
print(b*5)



[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]


In [37]:
np.eye(5)
np.eye(4,3)
b = np.eye(5)
b = np.eye(5,k=1)
b = np.eye(5,k=-1)
b

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
a = np.arange(start=0,stop=10,step=2)
a = np.arange(1,10)
a = np.arange(1,10,2.5)
a = np.arange(10,1,-3)

a

array([10,  7,  4])

In [55]:
a1 = np.linspace(1,10,4)
a1
a2 = np.linspace(1,2,10)
a2
a3 = np.linspace(1,6,100)
a3
a4 = np.logspace(1,10,10,base=2)
a4

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [ ]:
a1 = np.arange(1,10,dtype=int)
print(a1.astype('f'))





[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [61]:
a = np.array([1,True,False],dtype=int)
print(a)

[1 1 0]


In [65]:
a = np.random.uniform(1,5,(10,10))
print(a)

[[3.87454158 3.12577877 1.82174607 1.2249939  3.88042751 1.70771522
  1.77799125 1.54679168 2.12104263 3.35176827]
 [1.59140221 1.65755478 3.36117294 2.8439045  4.95143886 3.00429141
  3.21701134 4.73870394 4.8993376  2.72575422]
 [3.44551851 1.66447658 2.62187095 3.52912798 2.79976131 1.66715461
  2.18545913 2.84611814 2.38251148 1.3749791 ]
 [4.92097908 4.75132014 3.67808358 4.01305857 4.3314137  2.54014313
  2.10221614 4.34625898 1.94917604 4.77112654]
 [2.03754885 2.61742027 2.52834127 1.75057157 3.27061046 4.81628542
  1.19020001 3.13747677 3.63224273 4.23569022]
 [2.80992269 2.48409355 4.8147596  2.23322062 2.76360544 4.22193202
  4.08494181 1.40304974 2.95230169 1.61590343]
 [3.43676834 4.70528246 1.36436798 2.03596147 4.09353457 2.16573241
  1.53091395 1.47072519 1.26484194 4.87248822]
 [1.82864133 3.04294022 3.64635056 4.29589119 1.26589595 3.84325973
  3.85707529 2.18941896 2.90906098 2.35746869]
 [3.60507492 3.79331793 1.82669287 4.20528235 3.8993669  4.80586949
  3.93836081

In [ ]:
a = np.random.rand(10)
print(a)

array([0.9780346 , 0.89858651, 0.40172951, 0.01430592, 0.57066417,
       0.3211514 , 0.32960699, 0.50874592, 0.20868601, 0.78261751])

In [45]:
a = np.array([23,4,5,6,718])
print(np.random.choice(a,10))

[718   6 718 718   4   6   6 718   6 718]


In [79]:
a = np.array([23,4,5,6,718])
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)

(5,)
int64
1
5
8


In [86]:
a = np.array([[1,2],[3,4]])
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)

(2, 2)
int64
2
4
8


In [102]:
x = np.arange(1,10)
print(x)
b = x[ [1,2,3]]
z = x[[1,2,1,2,1,2,1,2]]
print(b)
print(z)

c = np.array([[1,2,3],
              [7,8,9],
              [10,11,12]])
print(c[[1,2],[1]])

[1 2 3 4 5 6 7 8 9]
[2 3 4]
[2 3 2 3 2 3 2 3]
[ 8 11]


In [ ]:
X = np.array([10,-3,-1,11,-11,5,10])
print(X[X<0])
print(X[X>0])
print(X[X==10])

[ -3  -1 -11]
[10 11  5 10]
[10 10]


In [115]:
X = np.array([[10,2,7],[3,5,1]])
b = np.array([1,2,3] )
print(X+b)

[[11  4 10]
 [ 4  7  4]]


In [17]:
import numpy as np
a1 = np.arange(1,11)
print(a1)
ar = np.reshape(a1,[2,5]) 
print(ar)
ar = np.reshape(ar,[5,2])
print(ar)
ar = np.reshape(ar,[1,10])
print(ar)
ar = np.reshape(ar,10)
print(ar)
ar.reshape([2,5])
print(ar)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [27]:
arr = np.arange(1,13)
a = np.reshape(arr,[3,-1])
a
b = np.reshape(arr,[2,-1])
b
c = np.reshape(arr,[-1,3])
c


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
arr = np.arange(1,13)
a = np.resize(arr,[2,6])
arr[0] = 15
print(arr)
print(a)

[15  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [30]:
a = np.array([[1,2],[3,4],[5,6]]) 
b = a.flatten()
a[0,0] = 2
print(a)
print(b)

[[2 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [33]:
a = np.array([[1,2],[3,4],[5,6]]) 
c = a.ravel()
a[0,0] = 2
print(a)
print(c)
c[0] = 3
print(a)
print(c)

[[2 2]
 [3 4]
 [5 6]]
[2 2 3 4 5 6]
[[3 2]
 [3 4]
 [5 6]]
[3 2 3 4 5 6]


In [46]:
import numpy as np
a = [[1,2,3],
     [4,5,6]]
a = np.array(a)
print(a.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [47]:
a = np.array([[1,2],
              [4,5]])
b = np.array([[11,12],
              [13,14]])
c = a.dot(b)
d = b.dot(a)
print(c)
print(d)

[[ 37  40]
 [109 118]]
[[59 82]
 [69 96]]


In [56]:
a = np.array([[1,2,3],
              [4,5,6],
              [1,3,-4]])
print('sum axis 0', np.sum(a,axis=0))
print('sum axis 1',np.sum(a,axis=1))
print('prod axis 0', np.prod(a,axis=0))
print('prod axis 1',np.prod(a,axis=1))
print('min axis 0', np.min(a,axis=0))
print('min axis 1',np.min(a,axis=1))
print('max axis 0', np.max(a,axis=0))
print('max axis 1',np.max(a,axis=1))
print('mean axis 0', np.mean(a,axis=0))
print('mean axis 1',np.mean(a,axis=1))

print('argmin axis 0', np.argmin(a,axis=0))
print('argmin axis 1',np.argmin(a,axis=1))

print('argmax axis 0', np.argmax(a,axis=0))
print('argmax axis 1',np.argmax(a,axis=1))

sum axis 0 [ 6 10  5]
sum axis 1 [ 6 15  0]
prod axis 0 [  4  30 -72]
prod axis 1 [  6 120 -12]
min axis 0 [ 1  2 -4]
min axis 1 [ 1  4 -4]
max axis 0 [4 5 6]
max axis 1 [3 6 3]
mean axis 0 [2.         3.33333333 1.66666667]
mean axis 1 [2. 5. 0.]
argmin axis 0 [0 0 2]
argmin axis 1 [0 0 2]
argmax axis 0 [1 1 1]
argmax axis 1 [2 2 1]


In [61]:
mode = np.arange(1,11)
print(mode)
np.append(mode,42)

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 42])

In [63]:
mode = np.arange(1,11)
print(mode)
np.insert(mode,1,100)
np.insert(mode,(1,4),100)

[ 1  2  3  4  5  6  7  8  9 10]


array([  1, 100,   2,   3,   4, 100,   5,   6,   7,   8,   9,  10])

In [66]:
a = np.array([[1,2],
              [3,4]])
print(a)
np.insert(a,1,100,axis=0)
np.insert(a,1,(100,20),axis=0)
np.insert(a,1,(100,20),axis=1)

[[1 2]
 [3 4]]


array([[  1, 100,   2],
       [  3,  20,   4]])

In [67]:
mode = np.arange(1,11)
print(mode)
mode = np.delete(mode,0)
print(mode)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10]


In [69]:
b = np.array([[1,2,3],
              [4,5,6],
              [1,3,-4]])
print(b)
b = np.delete(b,2,axis=0)
print(b)
b = np.delete(b,1,axis=1)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 1  3 -4]]
[[1 2 3]
 [4 5 6]]
[[1 3]
 [4 6]]


In [77]:
mode = np.arange(1,11)
print(mode)
mode = np.split(mode,5)
print(mode)
b = np.array([[1,2,3,5],
              [4,5,6,5],
              [1,3,-4,5]])
h = np.hsplit(b,2)
print(h)
v = np.vsplit(b,3)
print(v)


[ 1  2  3  4  5  6  7  8  9 10]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
[array([[1, 2],
       [4, 5],
       [1, 3]]), array([[ 3,  5],
       [ 6,  5],
       [-4,  5]])]
[array([[1, 2, 3, 5]]), array([[4, 5, 6, 5]]), array([[ 1,  3, -4,  5]])]


In [79]:
a1 = np.random.randint(10,21,10)
a2 = np.random.randint(30,41,10)

arr = np.concatenate([a1,a2])
print(arr)

[19 19 19 17 12 16 14 13 13 15 32 36 39 30 32 33 40 30 31 39]


In [87]:
a1 = np.random.randint(1,10,(2,2))
a2 = np.random.randint(1,10,(2,2))
print(a1)
print(a2)
v = np.vstack([a1,a2])
print(v)
h = np.hstack([a1,a2])
print(h)

[[3 3]
 [3 2]]
[[8 6]
 [2 1]]
[[3 3]
 [3 2]
 [8 6]
 [2 1]]
[[3 3 8 6]
 [3 2 2 1]]
