# pip install numpy

In [2]:
import numpy as np
mylist = [1,2,3,4,5]
mynum = np.array(mylist)
print(mynum)
type(mylist)

[1 2 3 4 5]


list

In [18]:
num2 = np.array([1,2,4])
num2

array([1, 2, 4])

In [19]:
num3 = np.array((1,2,4))
num3

array([1, 2, 4])

In [20]:
num4 = np.array({4,5,6})
num4

array({4, 5, 6}, dtype=object)

In [21]:
print(type(num4))

<class 'numpy.ndarray'>


In [26]:
A = [1.5,2,3,5]
B = (4,5,6,7)
A = np.array(A)
B = np.array(B)
type(A)
type(B)
print((A+B)*B)

[22. 35. 54. 84.]


In [23]:
print(A-B)
print(A*B)
print(A/B)

[-3 -3 -3 -2]
[ 4 10 18 35]
[0.25       0.4        0.5        0.71428571]


In [27]:
print(A.dtype)

float64


In [31]:
data = [20,30,31,35,40,42]
print(np.mean(data))
print(np.max(data))
print(np.min(data))
print(np.sum(data))

33.0
42
20
198


In [63]:
import numpy as np
data = np.random.randint(1,100,(10,10,10))
data

array([[[25, 82, 50, 41, 13, 56, 75, 12, 13, 19],
        [73,  7, 93,  6, 26, 12,  2, 92, 59, 40],
        [65, 90,  2, 19, 87, 37, 60,  8, 32,  9],
        [96, 69, 45, 84, 98, 66, 42, 48, 65, 92],
        [98, 18,  3, 50, 35, 70, 27, 41, 90, 91],
        [93, 34, 40, 68, 16, 74, 73, 76,  4, 29],
        [16,  1, 22, 98, 38, 24, 85, 32, 28, 48],
        [22, 60, 96, 33, 35, 78, 29, 95, 82, 78],
        [18,  7, 48, 15, 37,  2, 31, 47, 60, 30],
        [42, 92, 12, 40, 97, 51, 90, 28, 79, 19]],

       [[21,  4, 31, 57,  2, 49, 68, 50, 41, 15],
        [20, 88, 49, 49, 90, 12, 64, 44, 13, 17],
        [22, 91, 57, 24, 31, 48, 63,  9, 45, 67],
        [92, 91,  3, 93, 94, 51, 77, 79, 58, 33],
        [32, 60, 60, 33,  1, 82, 65, 98, 85, 41],
        [97, 50, 99, 91, 54, 22, 75, 66, 66, 43],
        [78, 33, 40, 97, 90, 26, 60, 86,  1, 46],
        [43, 94,  6, 56, 49, 87, 84, 13, 19, 76],
        [21, 20, 27, 22, 50, 92, 12, 45, 55, 72],
        [32, 86,  3, 40, 82, 68, 79, 31, 23, 42]

In [3]:
A = np.array([1,2,3,4])
A

array([1, 2, 3, 4])

In [5]:
B = [[1,2,3],
     [1,2,3],
     [2,3,4]]
B = np.array(B)
B

array([[1, 2, 3],
       [1, 2, 3],
       [2, 3, 4]])

In [7]:
C = [[[1,2],[2,3]],[[2,3],[5,6]],[[4,5],[4,6]]]
C = np.array(C)
print(C.shape)

(3, 2, 2)


In [8]:
D =  [[[1,2,6],[2,4,3]],[[2,3,7],[5,4,6]]]
D = np.array(D)
print(D.shape)

(2, 2, 3)


In [ ]:
arr = np.zeros(5)
arr = np.zeros((4,4))
arr = np.ones(5)
arr = np.ones((5,5),dtype=int)
arr = np.full((10,10),7)


print(arr)

[[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]


In [25]:
arr = np.array((True,False))
arr

array([ True, False])

In [59]:
import numpy as np

t = np.array([1,2,3,4])
arr = np.array( [[10,20,30],
                [100,200,300],
                [1000,2000,3000],
                [10000,20000,30000]])

t[0:4]
arr[0:2,0:2]
arr[1:4,2]
arr[1:,2:]

array([[  300],
       [ 3000],
       [30000]])